/// @description Wait a second before basing things off of num
alarm[0] = 1;
alarm[3] = 300;

depth = 0;
pushing = 0.8;
respawnTimer = 0;
setRespawnTimer = 3;
hp = 250;
maxhp = 250;
healing = 1;
dc = 90;
jug = false;
xp = 0;
yp = 0;
sameTeam = true;
invPass = false;
scale = 1;
invis = true;
totalDamage = 0;
vis = true;
firePassive = 0;
garren = false
gunDir = 0;
ramming = false
lastSpd = 0;
fireRate = 1;
lifeSteal = 0;
atk = 1;
magic = 1;
throwTime = 0;
wallPassive = false;
//layer = 1;
ammo = 10;
maxAmmo = 10;
seen = 0;
spectating = false;
walkDirection = 1;

image_yscale = 2;
image_speed = 1/2;

position_known = false;

//Status vars
inversion = 0;
jam = 0;
dashing = 0;
magicBurn = 0;
glassShield = 0;
controlled = 0;
controlledNum = 0;
controlledX = 0;
controlledY = 0;
milked = 0;
confuse = 0;
shield = 0;
chummed = 0;
marked = 0;
ghosting = 0;
drowsy = 0;
sleeping = 0;
poison = 0;
spellShield = 0;
decay = 0;
broken = 0;
frost = 0;
burn = 0;
tossGrabbed = 0;
oil = 0;
stunned = 0;
cryo = 0;
magicShield = 0;
blocking = 0;
bleed = 0;
murderball = 0
enraged = false;
enrageNum = 0;
kicking = 0;
scope = 1;
accuracy = 1;
quickTap = 0;

shadow = instance_create(x,y+30,obj_shadow);
shadow.link = self;
shadow.depth = 600;
cdr = 1;

xspd = 0;
yspd = 0;
movementPrediction = 0;
serverSendDamage = 0; //specifically for ai dealing dm to monsters