/// @description Have num = 1 but that'll change in 1 frame
num = 1;
col = c_teal;
center = fa_left;
alarm[0] = 1;
named = "hehaw";
team = -1;
xp = 0;
loadout = [spr_airstrike]
loadoutPicked = false;
height = 55;