/// @description Set all abilities
alarm[0] = 1;
cleaver = new Cleaver();
block = new Block();
molotov = new Molotov();
healBomb = new HealBomb();
dash = new Dash();
flash = new Flash();
shuriken = new Shuriken();
hook = new Hook();
heal = new Heal();
bloodshot = new Bloodshot();
bump = new Bump();
rocket = new Rocket();
flareGun = new FlareGun();
ghost = new Ghost();
reflect = new Reflect();
armorBreak = new ArmorBreak(); 
sleepDart = new SleepDart();
ninjaSlash = new NinjaDash();
blastOff = new BlastOff();
bat = new Bat();
teleport = new Teleport();
curse = new Curse();
poisonDagger = new PoisonDagger();
shatter = new Shatter();
wall = new Wall();
implosion = new Implosion();
chomp = new Chomp();
finisher = new Finisher()
holster = new Holster()
frost = new Frost();
axe = new Axe();
duelBomb = new DuelBomb()
swapper = new Swapper();
push = new Push();
chainbreaker = new Chainbreaker();
upgrade = new Upgrade();
deathtouch = new Deathtouch();
junglePotion = new JunglePotion();
revive = new Revive();
glassShield = new GlassShield();
rest = new Rest();
bodyslam = new BodySlam();
telekenesis = new Telekenesis();
kick = new Kick();
enrage = new Enrage();
milk = new Milk();
decay = new Decay();
glove = new Catch();

global.loadoutSet[0] = [shuriken, flash, bloodshot, frost, armorBreak, cleaver, healBomb, blastOff, obj_ARbullet, virgin_bullet];
global.loadoutSet[1] = [axe, dash, flareGun, molotov, block, rocket, implosion, blastOff, obj_grenade, obj_melee];
global.loadoutSet[2] = [heal, junglePotion, finisher, glassShield, revive, milk, healBomb, deathtouch, obj_shotgun, obj_bullet];
global.selectedLoadout = 1;