/// @description Set all abilities
alarm[0] = 1;
cleaver = new Cleaver();
block = new Block();
molotov = new Molotov();
healBomb = new HealBomb();
dash = new Dash();
flash = new Flash();
shuriken = new Shuriken();
hook = new Hook();
heal = new Heal();
bloodshot = new Bloodshot();
bump = new Bump();
rocket = new Rocket();
flareGun = new FlareGun();
ghost = new Ghost();
reflect = new Reflect();
armorBreak = new ArmorBreak(); 
sleepDart = new SleepDart();
ninjaSlash = new NinjaDash();
blastOff = new BlastOff();
bat = new Bat();
teleport = new Teleport();
curse = new Curse();
poisonDagger = new PoisonDagger();
shatter = new Shatter();
wall = new Wall();
implosion = new Implosion();
chomp = new Chomp();
finisher = new Finisher()
holster = new Holster()
frost = new Frost();
axe = new Axe();
duelBomb = new DuelBomb()
swapper = new Swapper();
push = new Push();
chainbreaker = new Chainbreaker();
upgrade = new Upgrade();
deathtouch = new Deathtouch();
junglePotion = new JunglePotion();
revive = new Revive();
glassShield = new GlassShield();
rest = new Rest();
bodyslam = new BodySlam();
telekenesis = new Telekenesis();

global.loadoutSet[0] = [shuriken, flash, dash, molotov, block, cleaver, healBomb, blastOff, obj_curve, obj_bullet];
global.loadoutSet[1] = [shuriken, flash, dash, molotov, block, cleaver, healBomb, blastOff, obj_curve, obj_bullet];
global.loadoutSet[2] = [shuriken, flash, dash, molotov, block, cleaver, healBomb, blastOff, obj_curve, obj_bullet];
global.selectedLoadout = 1;