/// @description Set text
tutText = "WASD to move. Click to shoot. \n Kill the dummy below"
//global.simple = false;
global.simple = false;
alarm[0] = 120;
textY = 675
textX = 550;
stage = -1;
arrowX = 0;
arrowY = 0;
arrowUp = true;
alarm[2] = 2;
//alarm[3] = 5;
global.levels = 10;
surface = false;
remindingText = false;
reminderTimer = 100;
textScale = 1;
textShake = 0;
textOffset = 0;